-- Universidades de Latinoamérica (fuente: Hipolabs Universities, dominio público)
-- Insertar después de schema.sql. Idempotente vía conflict on (name, country).

alter table institutions drop constraint if exists institutions_name_country_uniq;
alter table institutions add constraint institutions_name_country_uniq unique (name, country);

insert into institutions (name, country, website) values
  ('Benemerita Universidad Autónoma de Puebla', 'México', 'http://www.buap.mx/'),
  ('Brookdale Community College', 'Ecuador', 'http://www.brookdale.edu.ec/'),
  ('Caribbean University', 'Puerto Rico', 'http://www.caribbean.edu/'),
  ('Centro de Enseñanza Técnica Industrial', 'México', 'http://www.ceti.mx/'),
  ('Centro de Estudios Avanzados de Puerto Rico y el Caribe', 'Puerto Rico', 'http://www.ceaprc.org/'),
  ('Centro de Estudios Investigación y Tecnología (CEIT)', 'Colombia', 'http://www.iceit.edu.co/'),
  ('Centro de Estudios Universitarios Monterrey', 'México', 'http://www.ceu.edu.mx/'),
  ('Centro de Estudios Universitarios Xochicalco', 'México', 'http://www.ceux.mx/'),
  ('Centro de Investigación en Química Aplicada', 'México', 'https://ciqa.edu.mx'),
  ('Centro Regional Universitário de Espiríto Santo do Pinhal', 'Brasil', 'http://www.creupi.br/'),
  ('Centro Universitario Ciudad Vieja', 'Guatemala', 'http://www.cucv.edu.gt/'),
  ('Centro Universitario de Occidente', 'Guatemala', 'http://www.cunoc.edu.gt/'),
  ('Centro Universitario Ixtlahuaca', 'México', 'http://www.ceunix.com.mx/'),
  ('Centro Universitário Antônio Eufrásio de Toledo de Presidente Prudente - TOLEDO PRUDENTE', 'Brasil', 'https://toledoprudente.edu.br/'),
  ('Centro Universitário Barao de Maua', 'Brasil', 'http://www.baraodemaua.br/'),
  ('Centro Universitário Claretiano', 'Brasil', 'http://www.claretiano.edu.br/'),
  ('Centro Universitário de Araraquara', 'Brasil', 'http://www.uniara.com.br/'),
  ('Centro Universitário de Brasília, UNICEUB', 'Brasil', 'https://www.uniceub.br'),
  ('Centro Universitário De Goiás - UNIGOIÁS', 'Brasil', 'https://unigoias.com.br/'),
  ('Centro Universitário de João Pessoa', 'Brasil', 'http://www.unipe.br/'),
  ('Centro Universitário Facens - UniFACENS', 'Brasil', 'https://facens.br/'),
  ('Centro Universitário Monte Serrat', 'Brasil', 'http://www.unimonte.br/'),
  ('Centro Universitário Newton Paiva', 'Brasil', 'http://www.newtonpaiva.br/'),
  ('Centro Universitário Plinio Leite', 'Brasil', 'http://www.unipli.com.br/'),
  ('Centro Universitário Senac', 'Brasil', 'http://www.sp.senac.br/'),
  ('Centro Universitário Serra dos Órgãos', 'Brasil', 'http://www.unifeso.edu.br/'),
  ('Centro Universitário UniFatecie', 'Brasil', 'https://unifatecie.edu.br/'),
  ('Centro Universitário Álvares Penteado - FECAP', 'Brasil', 'https://www.fecap.br/'),
  ('CETYS Universidad', 'México', 'http://www.cetys.mx/'),
  ('Colegio de Estudios Superiores de Administración (CESA)', 'Colombia', 'http://www.cesa.edu.co/'),
  ('Colegio Mayor de Antioquia', 'Colombia', 'https://www.colmayor.edu.co/'),
  ('Columbus University', 'Panamá', 'http://www.columbus.edu/'),
  ('Conservatorio del Tolima', 'Colombia', 'http://www.bundenet.com/umusical/'),
  ('Corporación Educativa Mayor del Desarrollo "Simón Bolivar"', 'Colombia', 'http://www.unisimonbolivar.edu.co/'),
  ('Corporación Universitaria de Ibagué (CORUNIVERSITARIA)', 'Colombia', 'http://www.cui.edu.co/'),
  ('Corporación Universitaria de la Costa (UNICOSTA)', 'Colombia', 'http://www.cuc.edu.co/'),
  ('Corporación Universitaria de Santander (UDES)', 'Colombia', 'http://www.udes.edu.co/'),
  ('Corporación Universitaria Tecnológica de Bolivar', 'Colombia', 'http://www.cutb.edu.co/'),
  ('Cruzeiro do Sul University', 'Brasil', 'https://cruzeirodosul.edu.br'),
  ('Dirección General de Institutos Tecnológicos', 'México', 'http://www.dgit.gob.mx/'),
  ('El Colegio de México', 'México', 'http://www.colmex.mx/'),
  ('EMESCAM - Escola Superior de Ciências da Santa Casa de Misericórdia de Vitória', 'Brasil', 'http://www.emescam.br/'),
  ('Escuela Agricola Panamericana Zamorano', 'Honduras', 'http://www.zamorano.edu/'),
  ('Escuela Bancaria y Comercial', 'México', 'http://www.ebc.mx/'),
  ('Escuela Colombiana de Carreras Industriales', 'Colombia', 'http://www.ecci.edu.co/'),
  ('Escuela Colombiana de Ingeniería Julio Garavito', 'Colombia', 'http://www.escuelaing.edu.co/'),
  ('Escuela de Administración de Negocios', 'Colombia', 'http://www.ean.edu.co/'),
  ('Escuela de Arquitectura y Diseño', 'Chile', 'http://www.arquitecturaucv.cl/'),
  ('Escuela de Ingeniería de Antioquia', 'Colombia', 'http://www.eia.edu.co/'),
  ('Escuela de Policia "General Santander"', 'Colombia', 'http://www.escueladepolicia.edu.co/'),
  ('Escuela Nacional de Estudios Superiores Unidad León', 'México', 'http://www.enes.unam.mx/'),
  ('Escuela Politécnica de Chimborazo', 'Ecuador', 'http://www.espoch.edu/'),
  ('Escuela Politécnica del Ejercito', 'Ecuador', 'http://www.espe.edu.ec'),
  ('Escuela Politécnica Nacional', 'Ecuador', 'http://www.epn.edu.ec/'),
  ('Escuela Superior Politécnica del Litoral', 'Ecuador', 'http://www.espol.edu.ec/'),
  ('Escuela Superiore de Administración Pública', 'Colombia', 'http://www.esap.edu.co/'),
  ('Escuela Universitaria de Teología "Fundación Cardenal Pironio"', 'Argentina', 'https://eut.edu.ar/'),
  ('FAAP - Fundação Armando Alvares Penteado', 'Brasil', 'http://www.faap.br/'),
  ('Faculdade Do Instituto Nacional De Pós-Graduação - Faculdade INPG', 'Brasil', 'https://www.inpg.edu.br/'),
  ('Faculdade Dom Bosco', 'Brasil', 'https://faculdadedombosco.edu.br'),
  ('Faculdade Impacta - IMPACTA', 'Brasil', 'https://www.impacta.edu.br/'),
  ('Faculdade Integradas do Ceará', 'Brasil', 'http://www.fic.br/'),
  ('Faculdade Italo Brasileira', 'Brasil', 'http://www.italo.br/'),
  ('Faculdades Integradas Curitiba', 'Brasil', 'http://www.faculdadescuritiba.br/'),
  ('Faculdades Integradas do Brasil - UNIBRASIL', 'Brasil', 'http://www.unibrasil.com.br/'),
  ('Faculdades Integradas Toledo', 'Brasil', 'http://www.toledo.br/'),
  ('Faculdades Integradas UPIS', 'Brasil', 'http://www.upis.br/'),
  ('FAE Business School - Faculdade de Administração e Economia', 'Brasil', 'http://www.fae.edu/'),
  ('Federal Institute of Education', 'Brasil', 'https://ifsp.edu.br'),
  ('Floret Global University', 'Panamá', 'http://www.floret.edu.pa/'),
  ('Fundacion Escuela Colombiana de Rehabiliación', 'Colombia', 'http://www.ecr.edu.co/'),
  ('Fundación Universitaria de Boyacá', 'Colombia', 'http://www.uniboyaca.edu.co/'),
  ('Fundación Universitaria del Area Andina. Sede Pereira', 'Colombia', 'http://www.funandi.edu.co/'),
  ('Fundación Universitaria Luis Amigó', 'Colombia', 'http://www.funlam.edu.co/'),
  ('Fundación Universitaria Manuela Beltrán', 'Colombia', 'http://www.umb.edu.co/'),
  ('Fundación Universitaria San Martín', 'Colombia', 'http://www.sanmartin.edu.co/'),
  ('Fundação Educacional de Ituverava', 'Brasil', 'http://www.feituverava.com.br/'),
  ('Fundação Hermínio Ometto', 'Brasil', 'https://www.fho.edu.br/'),
  ('Insituto Universitario - Centro Latinoamericano de Economia Humana - IU Claeh', 'Uruguay', 'http://www.claeh.edu.uy/'),
  ('Insper Instituto de Ensino e Pesquisa', 'Brasil', 'https://www.insper.edu.br'),
  ('Institucion Universitaria de Envigado', 'Colombia', 'http://www.iue.edu.co/'),
  ('Institución Universitaria Iberoamericana', 'Colombia', 'http://www.iberoamericana.edu.co/'),
  ('Instituto de Enseñanza Superior del Ejército', 'Argentina', 'http://www.iese.edu.ar/'),
  ('Instituto de Enseñanza Superior Oteima', 'Panamá', 'http://www.institutoteima.ac.pa/'),
  ('Instituto de Estudios Superiores de la Sierra', 'México', 'http://www.ties.com.mx/'),
  ('Instituto de Tecnologia e Liderança - Inteli', 'Brasil', 'https://www.inteli.edu.br/'),
  ('Instituto Infnet', 'Brasil', 'https://www.infnet.edu.br/infnet/'),
  ('Instituto Mauá de Tecnologia', 'Brasil', 'http://www.maua.br/'),
  ('Instituto Militar de Engenharia', 'Brasil', 'http://www.ime.eb.mil.br'),
  ('Instituto Nacional de Matemática Pura e Aplicada - IMPA', 'Brasil', 'http://www.impa.br/'),
  ('Instituto Politécnico Nacional', 'México', 'http://www.ipn.edu.mx/'),
  ('Instituto Politécnico Nacional, Campus Guanajuato', 'México', 'http://www.upiig.ipn.mx/'),
  ('Instituto Superior Minero Metalúrgico "Dr. Antonio Núñez Jiménez"', 'Cuba', 'http://www.ismm.edu.cu/'),
  ('Instituto Superior Politécnico José Antonio Echeverría', 'Cuba', 'http://www.cujae.edu.cu/'),
  ('Instituto Tecnologico de Durango', 'México', 'http://www.itdurango.edu.mx/'),
  ('Instituto Tecnologico de Minatitlan', 'México', 'http://www.itmina.edu.mx/'),
  ('Instituto Tecnológico Autonómo de México', 'México', 'http://www.itam.mx/'),
  ('Instituto Tecnológico de Aeronáutica', 'Brasil', 'http://www.ita.br/'),
  ('Instituto Tecnológico de Aguascalientes', 'México', 'http://www.ita.mx/'),
  ('Instituto Tecnológico de Buenos Aires', 'Argentina', 'http://www.itba.edu.ar/'),
  ('Instituto Tecnológico de Celaya', 'México', 'http://www.itc.mx/'),
  ('Instituto Tecnológico de Costa Rica', 'Costa Rica', 'http://www.itcr.ac.cr/'),
  ('Instituto Tecnológico de Las Américas', 'República Dominicana', 'https://itla.edu.do/'),
  ('Instituto Tecnológico de León', 'México', 'http://www.itleon.edu.mx/'),
  ('Instituto Tecnológico de Morelia', 'México', 'http://www.itmorelia.edu.mx/'),
  ('Instituto Tecnológico de Occidente del Estado de Hidalgo', 'México', 'http://www.itsoeh.edu.mx/'),
  ('Instituto Tecnológico de Querétaro', 'México', 'http://www.itq.edu.mx/'),
  ('Instituto Tecnológico de San Luis Potosí', 'México', 'http://www.itslp.edu.mx/'),
  ('Instituto Tecnológico de Santo Domingo', 'República Dominicana', 'http://www.intec.edu.do/'),
  ('Instituto Tecnológico de Sonora', 'México', 'http://www.itson.mx/'),
  ('Instituto Tecnológico Metropolitano', 'Colombia', 'http://www.itm.edu.co/'),
  ('Instituto Tecnológico Superior de Nuevo Casas Grandes', 'México', 'http://itsncg.edu.mx/'),
  ('Instituto Tecnológico y de Estudios Superiores de Occidente', 'México', 'http://www.iteso.mx/'),
  ('Instituto Universitario Aeronáutico', 'Argentina', 'http://www.iua.edu.ar/'),
  ('Instituto Universitario CEMIC', 'Argentina', 'https://cemic.edu.ar/'),
  ('Instituto Universitario de Ciencias Biomédicas de Córdoba', 'Argentina', 'https://iucbc.edu.ar/'),
  ('Instituto Universitario de Ciencias de la Salud - Buenos Aires', 'Argentina', 'http://iucs.uncoma.edu.ar/'),
  ('Instituto Universitario de Estudios Navales y Marítimos', 'Argentina', 'http://www.inun.edu.ar/'),
  ('Instituto Universitario de La Paz', 'Colombia', 'http://www.unipaz.edu.co/'),
  ('Instituto Universitario de la Policía Federal', 'Argentina', 'http://www.universidad-policial.edu.ar/'),
  ('Instituto Universitario de Seguridad Marítima', 'Argentina', 'https://iusm.edu.ar/'),
  ('Instituto Universitario Gendarmería Nacional Argentina', 'Argentina', 'https://iugna.edu.ar/'),
  ('Instituto Universitario Italiano de Rosario', 'Argentina', 'https://iunir.edu.ar/'),
  ('Politécnico Columbiano "Jaime Isaza Cadavid"', 'Colombia', 'http://www.politecjic.edu.co/'),
  ('Politécnico de Guanajuato', 'México', 'http://www.poligto.edu.mx/'),
  ('Politécnico Grancolombiano - Institución Universitaria', 'Colombia', 'http://www.poligran.edu.co/'),
  ('Polytechnic University of Pernambuco', 'Brasil', 'https://upe.poli.br'),
  ('Pontificia Universidad Catolica de Chile', 'Chile', 'https://www.uc.cl/'),
  ('Pontificia Universidad Catolica de Puerto Rico', 'Puerto Rico', 'http://www.pucpr.edu/'),
  ('Pontificia Universidad Católica del Ecuador', 'Ecuador', 'http://www.puce.edu.ec/'),
  ('Pontificia Universidad Católica del Perú', 'Perú', 'http://www.pucp.edu.pe/'),
  ('Pontificia Universidad Javeriana', 'Colombia', 'http://www.javeriana.edu.co/'),
  ('Pontificia Universidade Católica do Paraná', 'Brasil', 'http://www.pucpr.br/'),
  ('Pontifícia Universidade Católica de Campinas', 'Brasil', 'http://www.puccamp.br/'),
  ('Pontifícia Universidade Católica de Minas Gerais', 'Brasil', 'http://www.pucminas.br/'),
  ('Pontifícia Universidade Católica de São Paulo', 'Brasil', 'http://www.pucsp.br/'),
  ('Pontifícia Universidade Católica do Rio de Janeiro', 'Brasil', 'http://www.puc-rio.br/'),
  ('Pontifícia Universidade Católica do Rio Grande do Sul', 'Brasil', 'http://www.pucrs.br/'),
  ('San Juan Bautista School of Medicine', 'Puerto Rico', 'http://www.sanjuanbautista.edu/'),
  ('Sistema Universitario Ana G. Méndez', 'Puerto Rico', 'http://www.suagm.edu/'),
  ('Tecnologico de Baja California, Universidad', 'México', 'http://www.tecbc.mx/'),
  ('Tecnologico de Monterrey', 'México', 'https://www.tec.mx/'),
  ('UNINOVE', 'Brasil', 'https://uninove.br'),
  ('Universidad "Arturo Prat"', 'Chile', 'http://www.unap.cl/'),
  ('Universidad "Juan Agustín Maza"', 'Argentina', 'http://www.umaza.edu.ar/'),
  ('Universidad Abierta Interamericana', 'Argentina', 'https://uai.edu.ar/'),
  ('Universidad Abierta Para Adultos', 'República Dominicana', 'http://www.uapa.edu.do/'),
  ('Universidad Abierta y a Distancia de Panama', 'Panamá', 'http://www.unadp.ac.pa/'),
  ('Universidad Academia de Humanismo Cristiano', 'Chile', 'http://www.academia.cl/'),
  ('Universidad Adolfo Ibáñez', 'Chile', 'http://www.uai.cl/'),
  ('Universidad Adventista de Centro América', 'Costa Rica', 'http://www.unadeca.ac.cr/'),
  ('Universidad Adventista de Chile', 'Chile', 'http://www.unachile.cl/'),
  ('Universidad Adventista de Colombia', 'Colombia', 'http://www.unac.edu.co/'),
  ('Universidad Adventista del Plata', 'Argentina', 'http://www.uapar.edu/'),
  ('Universidad Adventista Dominicana', 'República Dominicana', 'http://www.unad.edu.do/'),
  ('Universidad Agraria del Ecuador', 'Ecuador', 'http://www.uagraria.edu.ec/'),
  ('Universidad Agroforestal Fernando A.Meriño', 'República Dominicana', 'http://www.uafam.edu.do/'),
  ('Universidad Alas Peruanas', 'Perú', 'http://www.uap.edu.pe/'),
  ('Universidad Albert Einstein', 'El Salvador', 'http://www.uae.edu.sv/'),
  ('Universidad Alberto Hurtado', 'Chile', 'http://www.uahurtado.cl/'),
  ('Universidad Americana', 'Nicaragua', 'http://www.uam.edu.ni/'),
  ('Universidad Americana', 'Paraguay', 'http://www.uamericana.edu.py/'),
  ('Universidad Ana G. Méndez', 'Puerto Rico', 'https://uagm.edu'),
  ('Universidad Andina del Cusco', 'Perú', 'http://www.uandina.edu.pe/'),
  ('Universidad Andina Nestor Caceares Velasquez', 'Perú', 'http://www.uancv.edu.pe/'),
  ('Universidad Andina Simón Bolívar', 'Ecuador', 'http://www.uasb.edu.ec/'),
  ('Universidad Antonio Nariño', 'Colombia', 'http://www.uanarino.edu.co/'),
  ('Universidad Anáhuac', 'México', 'http://www.anahuac.mx/'),
  ('Universidad Anáhuac del Sur', 'México', 'http://www.uas.mx/'),
  ('Universidad APEC', 'República Dominicana', 'http://www.unapec.edu.do/'),
  ('Universidad Arcis', 'Chile', 'http://www.universidadarcis.cl/'),
  ('Universidad Argentina "John F. Kennedy"', 'Argentina', 'http://www.kennedy.edu.ar/'),
  ('Universidad Argentina de la Empresa', 'Argentina', 'http://www.uade.edu.ar/'),
  ('Universidad Atlántida Argentina', 'Argentina', 'http://www.atlantida.edu.ar/'),
  ('Universidad Austral Buenos Aires', 'Argentina', 'http://www.austral.edu.ar/'),
  ('Universidad Austral de Chile', 'Chile', 'http://www.uach.cl/'),
  ('Universidad Autonoma de Chiriqui', 'Panamá', 'http://www.unachi.ac.pa/'),
  ('Universidad Autonoma de Durango', 'México', 'http://www.uad.edu.mx/'),
  ('Universidad Autonoma del Sur', 'Chile', 'http://www.uas.cl/'),
  ('Universidad Autonoma España de Durango', 'México', 'http://www.uaed.edu.mx/'),
  ('Universidad Autonoma Monterrey', 'Costa Rica', 'http://www.unam.ac.cr/'),
  ('Universidad Autónoma "Benito Juárez" de Oaxaca', 'México', 'http://www.uabjo.mx/'),
  ('Universidad Autónoma Agraria "Antonio Narro"', 'México', 'http://www.uaaan.mx/'),
  ('Universidad Autónoma de Aguascalientes', 'México', 'http://www.uaa.mx:8001/'),
  ('Universidad Autónoma de Asunción', 'Paraguay', 'http://www.uaa.edu.py/'),
  ('Universidad Autónoma de Baja California', 'México', 'http://www.uabc.mx/'),
  ('Universidad Autónoma de Baja California Sur', 'México', 'http://www.uabcs.mx/'),
  ('Universidad Autónoma de Bucaramanga', 'Colombia', 'http://www.unab.edu.co/'),
  ('Universidad Autónoma de Campeche', 'México', 'http://www.uacam.mx/'),
  ('Universidad Autónoma de Centro América', 'Costa Rica', 'http://www.uaca.ac.cr/'),
  ('Universidad Autónoma de Chapingo', 'México', 'http://www.chapingo.mx/'),
  ('Universidad Autónoma de Chiapas', 'México', 'http://www.unach.mx/'),
  ('Universidad Autónoma de Chihuahua', 'México', 'http://www.uach.mx/'),
  ('Universidad Autónoma de Ciudad Juárez', 'México', 'http://www.uacj.mx/'),
  ('Universidad Autónoma de Coahuila', 'México', 'http://www.uadec.mx/'),
  ('Universidad Autónoma de Colombia', 'Colombia', 'http://www.fuac.edu.co/'),
  ('Universidad Autónoma de Entre Ríos', 'Argentina', 'http://www.uader.edu.ar/'),
  ('Universidad Autónoma de Fresnillo', 'México', 'http://www.uaf.mx/'),
  ('Universidad Autónoma de Guadalajara', 'México', 'http://www.uag.mx/'),
  ('Universidad Autónoma de Guerrero', 'México', 'http://www.uagro.mx/'),
  ('Universidad Autónoma de la Ciudad de México', 'México', 'http://www.uacm.edu.mx/'),
  ('Universidad Autónoma de la Laguna', 'México', 'http://www.ual.mx/'),
  ('Universidad Autónoma de Las Américas', 'Colombia', 'http://www.uam.edu.co/'),
  ('Universidad Autónoma de Manizales', 'Colombia', 'http://www.autonoma.edu.co/'),
  ('Universidad Autónoma de Nayarit', 'México', 'http://www.uan.mx/'),
  ('Universidad Autónoma de Nuevo León', 'México', 'http://www.uanl.mx/'),
  ('Universidad Autónoma de Occidente', 'Colombia', 'http://www.cuao.edu.co/'),
  ('Universidad Autónoma de Querétaro', 'México', 'http://www.uaq.mx/'),
  ('Universidad Autónoma de San Luis Potosí', 'México', 'http://www.uaslp.mx/'),
  ('Universidad Autónoma de Santa Ana', 'El Salvador', 'http://www.unasa.edu.sv/'),
  ('Universidad Autónoma de Santo Domingo', 'República Dominicana', 'http://www.uasd.edu.do/'),
  ('Universidad Autónoma de Sinaloa', 'México', 'http://www.uasnet.mx/'),
  ('Universidad Autónoma de Tamaulipas', 'México', 'http://www.uat.mx/'),
  ('Universidad Autónoma de Tlaxcala', 'México', 'http://www.uatx.mx/'),
  ('Universidad Autónoma de Veracruz Villa Rica', 'México', 'http://www.univillarica.mx/'),
  ('Universidad Autónoma de Yucatán', 'México', 'http://www.uady.mx/'),
  ('Universidad Autónoma de Zacatecas', 'México', 'http://www.reduaz.mx/'),
  ('Universidad Autónoma del Caribe', 'Colombia', 'http://www.uac.edu.co/'),
  ('Universidad Autónoma del Carmen', 'México', 'http://www.unacar.mx/'),
  ('Universidad Autónoma del Estado de Hidalgo', 'México', 'http://www.reduaeh.mx/'),
  ('Universidad Autónoma del Estado de Morelos', 'México', 'http://www.uaem.mx/'),
  ('Universidad Autónoma del Estado de México', 'México', 'http://www.uaemex.mx/'),
  ('Universidad Autónoma del Noreste', 'México', 'http://www.uane.edu.mx/'),
  ('Universidad Autónoma del Paraguay', 'Paraguay', 'http://www.uap.edu.py/'),
  ('Universidad Autónoma Latinoamericana', 'Colombia', 'http://www.unaula.edu.co/'),
  ('Universidad Autónoma Metropolitana', 'México', 'http://www.uam.mx/'),
  ('Universidad Autónoma Metropolitana - Azcapotzalco', 'México', 'https://azc.uam.mx/'),
  ('Universidad Autónoma Metropolitana - Iztapalapa', 'México', 'http://www.iztapalapa.uam.mx/'),
  ('Universidad Autónoma Metropolitana - Xochimilco', 'México', 'http://cueyatl.uam.mx/'),
  ('Universidad Bellas Artes', 'Colombia', 'http://www.bellasartes.edu.co/'),
  ('Universidad Bernardo O''Higgins', 'Chile', 'http://www.ubohiggins.cl/'),
  ('Universidad Blas Pascal', 'Argentina', 'http://www.ubp.edu.ar/'),
  ('Universidad Bolivariana', 'Chile', 'http://www.ubolivariana.cl/'),
  ('Universidad Braulio Carrillo', 'Costa Rica', 'http://www.universidadbrauliocarrillo.com/'),
  ('Universidad CAECE, Buenos Aires', 'Argentina', 'http://www.caece.edu.ar/'),
  ('Universidad Capitain General Gerardo Barrios', 'El Salvador', 'http://www.ugb.edu.sv/'),
  ('Universidad Casa Grande', 'Ecuador', 'http://www.casagrande.edu.ec/'),
  ('Universidad Catolica "Redemptoris Mater"', 'Nicaragua', 'http://www.unica.edu.ni/'),
  ('Universidad Catolica de Azogues', 'Ecuador', 'http://www.ucaazo.edu.ec/'),
  ('Universidad Catolica de La Santísima Concepción', 'Chile', 'http://www.ucsc.cl/'),
  ('Universidad Catolica de Temuco', 'Chile', 'http://www.uctem.cl/'),
  ('Universidad Catolica de Valparaiso', 'Chile', 'http://www.ucv.cl/'),
  ('Universidad Catolica del Maule', 'Chile', 'http://www.ucm.cl/'),
  ('Universidad Catolica del Norte', 'Chile', 'http://www.ucn.cl/'),
  ('Universidad Católica Anselmo Llorente', 'Costa Rica', 'http://www.ucatolica.ac.cr/'),
  ('Universidad Católica Argentina Santa Maria de los Buenos Aires', 'Argentina', 'http://www.uca.edu.ar/'),
  ('Universidad Católica Cardenal Raúl Silva Henríquez', 'Chile', 'http://www.ucsh.cl/'),
  ('Universidad Católica de Colombia', 'Colombia', 'http://www.ucatolica.edu.co/'),
  ('Universidad Católica de Cuenca', 'Ecuador', 'http://www.ucacue.edu.ec/'),
  ('Universidad Católica de Cuyo', 'Argentina', 'http://www.uccuyo.edu.ar/'),
  ('Universidad Católica de Córdoba', 'Argentina', 'http://www.uccor.edu.ar/'),
  ('Universidad Católica de Honduras', 'Honduras', 'http://www.unicah.edu/'),
  ('Universidad Católica de La Plata', 'Argentina', 'http://www.ucalp.edu.ar/'),
  ('Universidad Católica de Manizales', 'Colombia', 'http://www.ucatolicamz.edu.co/'),
  ('Universidad Católica de Occidente', 'El Salvador', 'http://www.unico.edu.sv/'),
  ('Universidad Católica de Salta', 'Argentina', 'http://www.ucasal.net/'),
  ('Universidad Católica de Santa Fe', 'Argentina', 'http://www.ucsf.edu.ar/'),
  ('Universidad Católica de Santa María', 'Perú', 'http://www.ucsm.edu.pe/'),
  ('Universidad Católica de Santiago de Guayaquil', 'Ecuador', 'http://www.ucsg.edu.ec/'),
  ('Universidad Católica de Santiago del Estero', 'Argentina', 'http://www.ucse.edu.ar/'),
  ('Universidad Católica de Santo Domingo', 'República Dominicana', 'http://www.ucsd.edu.do/'),
  ('Universidad Católica del Norte', 'Colombia', 'http://www.ucn.edu.co/'),
  ('Universidad Católica del Oriente', 'Colombia', 'http://www.uco.edu.co/'),
  ('Universidad Católica del Uruguay', 'Uruguay', 'http://www.ucu.edu.uy/'),
  ('Universidad Católica Madre y Maestra', 'República Dominicana', 'http://www.pucmm.edu.do/'),
  ('Universidad Católica Nordestana', 'República Dominicana', 'http://www.ucne.edu.do/'),
  ('Universidad Católica Nuestra Senora de la Asunción', 'Paraguay', 'http://www.uc.edu.py/'),
  ('Universidad Católica Popular del Risaralda', 'Colombia', 'http://www.ucpr.edu.co/'),
  ('Universidad Católica Santa María La Antigua', 'Panamá', 'http://www.usma.ac.pa/'),
  ('Universidad Católica Santo Toribio de Mogrovejo', 'Perú', 'http://www.usat.edu.pe/'),
  ('Universidad Católica Tecnológica del Cibao', 'República Dominicana', 'http://www.ucateci.edu.do/'),
  ('Universidad Central', 'Chile', 'http://www.ucentral.cl/'),
  ('Universidad Central', 'Colombia', 'http://www.ucentral.edu.co/'),
  ('Universidad Central', 'Costa Rica', 'http://www.universidadcentral.com/'),
  ('Universidad Central de Bayamón', 'Puerto Rico', 'http://www.ucb.edu.pr/'),
  ('Universidad Central de Las Villas', 'Cuba', 'http://www.uclv.edu.cu/'),
  ('Universidad Central del Caribe', 'Puerto Rico', 'http://www.uccaribe.edu/'),
  ('Universidad Central del Ecuador', 'Ecuador', 'http://www.ucentral.edu.ec/'),
  ('Universidad Central del Este', 'República Dominicana', 'http://www.uce.edu.do/'),
  ('Universidad Central del Valle del Cauca', 'Colombia', 'http://www.uceva.edu.co/'),
  ('Universidad Centroamericana', 'Nicaragua', 'http://www.uca.edu.ni/'),
  ('Universidad Centroamericana "José Simeón Canas"', 'El Salvador', 'http://www.uca.edu.sv/'),
  ('Universidad Centroamericana de Ciencias Empresariales (UCEM)', 'Nicaragua', 'http://www.ucem.edu.ni/'),
  ('Universidad CES', 'Colombia', 'http://www.ces.edu.co/'),
  ('Universidad Champagnat', 'Argentina', 'http://www.uch.edu.ar/'),
  ('Universidad Champagnat', 'México', 'http://www.champagnat.edu.mx/'),
  ('Universidad Chapultepéc', 'México', 'http://www.univchapultepec.edu.mx/'),
  ('Universidad Chileno Britanica de Cultura', 'Chile', 'http://www.ubritanica.cl/'),
  ('Universidad Ciencias Comerciales', 'Nicaragua', 'http://www.ucc.edu.ni/'),
  ('Universidad Cientifica del Sur', 'Perú', 'http://www.ucsur.edu.pe/'),
  ('Universidad Cientifica Latinoamericana de Hidalgo', 'México', 'http://www.uclah.edu.mx/'),
  ('Universidad Columbia del Paraguay', 'Paraguay', 'http://www.columbia.edu.py/'),
  ('Universidad Comunera', 'Paraguay', 'http://www.ucom.edu.py/'),
  ('Universidad Cooperativa de Colombia', 'Colombia', 'http://www.ucc.edu.co/'),
  ('Universidad Cristiana de las Asambleas de Dios', 'El Salvador', 'http://www.ucad.edu.sv/'),
  ('Universidad Cristóbal Colón', 'México', 'http://www.ver.ucc.mx/'),
  ('Universidad Cuauhtémoc', 'México', 'http://www.cuauhtemoc.edu.mx/'),
  ('Universidad César Vallejo', 'Perú', 'http://www.ucv.edu.pe/'),
  ('Universidad de Aconcagua', 'Chile', 'http://www.uaconcagua.cl/'),
  ('Universidad de América Bogotá', 'Colombia', 'http://www.uamerica.edu.co/'),
  ('Universidad de Antioquía', 'Colombia', 'http://www.udea.edu.co/'),
  ('Universidad de Antofagasta', 'Chile', 'http://www.uantof.cl/'),
  ('Universidad de Artes, Ciencias y Comunicación', 'Chile', 'http://www.uniacc.cl/'),
  ('Universidad de Atacama', 'Chile', 'http://www.uda.cl/'),
  ('Universidad de Aysen', 'Chile', 'https://www.uaysen.cl/'),
  ('Universidad de Belgrano', 'Argentina', 'http://www.ub.edu.ar/'),
  ('Universidad de Bogotá "Jorge Tadeo Lozano"', 'Colombia', 'http://www.utadeo.edu.co/'),
  ('Universidad de Bologna - Representación en Buenos Aires', 'Argentina', 'http://www.unibo.edu.ar/'),
  ('Universidad de Buenos Aires', 'Argentina', 'http://www.uba.ar/'),
  ('Universidad de Caldas', 'Colombia', 'http://www.ucaldas.edu.co/'),
  ('Universidad de Camagüey', 'Cuba', 'http://www.reduc.edu.cu/'),
  ('Universidad de Cartagena', 'Colombia', 'http://www.unicartagena.edu.co/'),
  ('Universidad de Cartago', 'Panamá', 'http://www.ucapanama.org/'),
  ('Universidad de Cartago Florencio del Castillo', 'Costa Rica', 'http://www.uca.ac.cr/'),
  ('Universidad de Celaya', 'México', 'http://www.udec.edu.mx/'),
  ('Universidad de Chile', 'Chile', 'http://www.uchile.cl/'),
  ('Universidad de Ciego de Avila', 'Cuba', 'http://www.unica.cu/'),
  ('Universidad de Ciencias Aplicadas y Ambientales (UDCA)', 'Colombia', 'http://www.udca.edu.co/'),
  ('Universidad de Ciencias de la Informatica', 'Chile', 'http://www.ucinf.cl/'),
  ('Universidad de Ciencias Empresariales y Sociales', 'Argentina', 'http://www.uces.edu.ar/'),
  ('Universidad de Ciencias Médicas', 'Costa Rica', 'https://ucimed.com/'),
  ('Universidad de Ciencias y Artes de Chiapas', 'México', 'http://www.unicach.edu.mx/'),
  ('Universidad de Ciencias y Humanidades', 'Perú', 'http://www.uch.edu.pe/'),
  ('Universidad de Cienfuegos', 'Cuba', 'http://www.ucf.edu.cu/'),
  ('Universidad de Colima', 'México', 'http://www.ucol.mx/'),
  ('Universidad de Comunicación Avanzada', 'México', 'http://www.unica.edu.mx/'),
  ('Universidad de Concepcion', 'Chile', 'http://www.udec.cl/'),
  ('Universidad de Concepción del Uruguay', 'Argentina', 'http://www.ucu.edu.ar/'),
  ('Universidad de Congreso', 'Argentina', 'http://www.ucongres.edu.ar/'),
  ('Universidad de Costa Rica', 'Costa Rica', 'http://www.ucr.ac.cr/'),
  ('Universidad de Cuautitlan Izcalli', 'México', 'http://www.udeci.edu.mx/'),
  ('Universidad de Cuenca', 'Ecuador', 'http://www.ucuenca.edu.ec/'),
  ('Universidad de Córdoba', 'Colombia', 'http://www.unicordoba.edu.co/'),
  ('Universidad de El Salvador', 'El Salvador', 'http://www.ues.edu.sv/'),
  ('Universidad de Especialidades del Espíritu Santo', 'Ecuador', 'http://www.uees.edu.ec/'),
  ('Universidad de Especialidades Turísticas', 'Ecuador', 'http://www.uct.edu.ec/'),
  ('Universidad de Flores - Buenos Aires', 'Argentina', 'http://www.uflo.edu.ar/'),
  ('Universidad de Granma', 'Cuba', 'http://www.udg.co.cu/'),
  ('Universidad de Guadalajara', 'México', 'http://www.udg.mx/'),
  ('Universidad de Guanajuato', 'México', 'http://www.ugto.mx/'),
  ('Universidad de Guanajuato, Campus León', 'México', 'http://www.campusleon.ugto.mx/'),
  ('Universidad de Guayaquil', 'Ecuador', 'http://www.ug.edu.ec/'),
  ('Universidad de Hermosillo', 'México', 'http://www.udeh.edu.mx/'),
  ('Universidad de Holguín', 'Cuba', 'http://www.uho.edu.cu/'),
  ('Universidad de Huánuco', 'Perú', 'http://www.udh.edu.pe/'),
  ('Universidad de Iberoamérica', 'Costa Rica', 'http://www.unibe.ac.cr/'),
  ('Universidad de Ingeniería y Tecnología', 'Perú', 'https://utec.edu.pe/'),
  ('Universidad de La Amazonia', 'Colombia', 'http://www.uniamazonia.edu.co/'),
  ('Universidad de la Cuenca del Plata', 'Argentina', 'http://www.ucp.edu.ar/'),
  ('Universidad de la Defensa Nacional', 'Argentina', 'https://undef.edu.ar/'),
  ('Universidad de la Empresa (UDE)', 'Uruguay', 'http://www.ude.edu.uy/'),
  ('Universidad de la Fraternidad de Agrupaciones Santo Tomás de Aquino (FASTA)', 'Argentina', 'http://www.ufasta.edu.ar/'),
  ('Universidad de La Frontera', 'Chile', 'http://www.ufro.cl/'),
  ('Universidad de La Guajira', 'Colombia', 'http://www.uniguajira.edu.co/'),
  ('Universidad de La Habana', 'Cuba', 'http://www.uh.cu/'),
  ('Universidad de la Integración de las Americas (UNIDAD)', 'Paraguay', 'http://www.unida.edu.py/'),
  ('Universidad de la Marina Mercante', 'Argentina', 'http://www.udemm.edu.ar/'),
  ('Universidad de la República', 'Uruguay', 'http://www.universidad.edu.uy/'),
  ('Universidad de La Sabana', 'Colombia', 'http://www.unisabana.edu.co/'),
  ('Universidad de La Salle', 'Colombia', 'http://www.lasalle.edu.co/'),
  ('Universidad de La Salle', 'Costa Rica', 'http://www.ulasalle.ac.cr/'),
  ('Universidad de La Salle, Bajío', 'México', 'http://bajio.delasalle.edu.mx/'),
  ('Universidad de La Serena', 'Chile', 'http://www.userena.cl/'),
  ('Universidad de la Sierra A.C.', 'México', 'http://www.usac.edu.mx/'),
  ('Universidad de la Tercera Edad', 'República Dominicana', 'http://www.ute.edu.do/'),
  ('Universidad de Lambayeque', 'Perú', 'http://www.udl.edu.pe/'),
  ('Universidad de Las Américas', 'Chile', 'http://www.uamericas.cl/'),
  ('Universidad de las Américas', 'México', 'http://www.udla.mx/'),
  ('Universidad de las Américas (ULAM)', 'Nicaragua', 'http://www.ulam.edu.ni/'),
  ('Universidad de las Américas - Puebla', 'México', 'http://www.udlap.mx/'),
  ('Universidad de las Regiones Autónomas de la Costa Caribe Nicaragüense', 'Nicaragua', 'http://www.uraccan.edu.ni/'),
  ('Universidad de León', 'México', 'http://www.universidaddeleon.edu.mx/'),
  ('Universidad de Lima', 'Perú', 'http://www.ulima.edu.pe/'),
  ('Universidad de Los Andes', 'Chile', 'http://www.uandes.cl/'),
  ('Universidad de Los Andes', 'Colombia', 'http://www.uniandes.edu.co/'),
  ('Universidad de Los Lagos', 'Chile', 'http://www.ulagos.cl/'),
  ('Universidad de Los Llanos', 'Colombia', 'http://www.unillanos.edu.co/'),
  ('Universidad de Magallanes', 'Chile', 'http://www.umag.cl/'),
  ('Universidad de Managua (U de M)', 'Nicaragua', 'http://www.udem.edu.ni/'),
  ('Universidad de Manizales', 'Colombia', 'http://www.umanizales.edu.co/'),
  ('Universidad de Matanzas Camilo Cienfuegos', 'Cuba', 'http://www.umcc.cu/'),
  ('Universidad de Medellín', 'Colombia', 'http://www.udem.edu.co/'),
  ('Universidad de Mendoza', 'Argentina', 'http://www.um.edu.ar/'),
  ('Universidad de Montemorelos', 'México', 'http://www.umontemorelos.edu.mx/'),
  ('Universidad de Monterrey', 'México', 'http://www.udem.edu.mx/'),
  ('Universidad de Montevideo', 'Uruguay', 'http://www.um.edu.uy/'),
  ('Universidad de Morón', 'Argentina', 'http://www.unimoron.edu.ar/'),
  ('Universidad de Nariño', 'Colombia', 'http://www.udenar.edu.co/'),
  ('Universidad de Norteamerica', 'México', 'http://www.un.mx/'),
  ('Universidad de Occidente', 'México', 'http://www.udo.mx/'),
  ('Universidad de Oriente', 'Cuba', 'http://www.uo.edu.cu/'),
  ('Universidad de Oriente', 'El Salvador', 'http://www.univo.edu.sv/'),
  ('Universidad de Palermo', 'Argentina', 'http://www.palermo.edu/'),
  ('Universidad de Pamplona', 'Colombia', 'http://www.unipamplona.edu.co/'),
  ('Universidad de Panamá', 'Panamá', 'http://www.up.ac.pa/'),
  ('Universidad de Pinar del Río', 'Cuba', 'http://www.upr.edu.cu/'),
  ('Universidad de Piura', 'Perú', 'http://www.udep.edu.pe/'),
  ('Universidad de Playa Ancha de Ciencias de la Educacion', 'Chile', 'http://www.upa.cl/'),
  ('Universidad de Puerto Rico', 'Puerto Rico', 'http://www.upr.clu.edu/'),
  ('Universidad de Puerto Rico, Aguadilla', 'Puerto Rico', 'http://www.uprag.edu/'),
  ('Universidad de Puerto Rico, Arecibo', 'Puerto Rico', 'http://www.upra.edu/'),
  ('Universidad de Puerto Rico, Bayamon', 'Puerto Rico', 'http://www.uprb.edu/'),
  ('Universidad de Puerto Rico, Carolina', 'Puerto Rico', 'http://www.uprc.edu/'),
  ('Universidad de Puerto Rico, Cayey', 'Puerto Rico', 'http://www.cayey.upr.edu/'),
  ('Universidad de Puerto Rico, Ciencias Medicas', 'Puerto Rico', 'http://www.rcm.upr.edu/'),
  ('Universidad de Puerto Rico, Humacao', 'Puerto Rico', 'http://cuhwww.upr.clu.edu/'),
  ('Universidad de Puerto Rico, Mayaguez', 'Puerto Rico', 'http://www.uprm.edu/'),
  ('Universidad de Puerto Rico, Ponce', 'Puerto Rico', 'http://upr-ponce.upr.edu/'),
  ('Universidad de Puerto Rico, Rio Pedras', 'Puerto Rico', 'http://www.uprrp.edu/'),
  ('Universidad de Puerto Rico, Utuado', 'Puerto Rico', 'http://www.uprutuado.edu/'),
  ('Universidad de Quintana Roo', 'México', 'http://www.uqroo.mx/'),
  ('Universidad de San Andres', 'Chile', 'http://www.usanandres.cl/'),
  ('Universidad de San Andrés', 'Argentina', 'http://www.udesa.edu.ar/'),
  ('Universidad de San Buenaventura', 'Colombia', 'http://www.usb.edu.co/'),
  ('Universidad de San Buenaventura Medellin', 'Colombia', 'http://www.usbmed.edu.co/'),
  ('Universidad de San Carlos de Guatemala', 'Guatemala', 'http://www.usac.edu.gt/'),
  ('Universidad de San José', 'Costa Rica', 'http://www.universidadsanjosecr.com/'),
  ('Universidad de San Miguel', 'México', 'http://www.udesanmiguel.edu.mx/'),
  ('Universidad de San Pablo - Tucumán', 'Argentina', 'https://uspt.edu.ar/'),
  ('Universidad de San Pedro Sula', 'Honduras', 'http://www.usps.edu.hn/'),
  ('Universidad de Santiago de Chile', 'Chile', 'http://www.usach.cl/'),
  ('Universidad de Sonora', 'México', 'http://www.uson.mx/'),
  ('Universidad de Sonsonate', 'El Salvador', 'http://www.usonsonate.edu.sv/'),
  ('Universidad de Sucre', 'Colombia', 'http://www.unisucre.edu.co/'),
  ('Universidad de Talca', 'Chile', 'http://www.utalca.cl/'),
  ('Universidad de Tarapacá', 'Chile', 'http://www.uta.cl/'),
  ('Universidad de Valparaiso', 'Chile', 'http://www.uv.cl/'),
  ('Universidad de Viña del Mar', 'Chile', 'http://www.uvm.cl/'),
  ('Universidad del Aconcagua', 'Argentina', 'http://www.uda.edu.ar/'),
  ('Universidad del Atlántico', 'Colombia', 'http://www.uniatlantico.edu.co/'),
  ('Universidad del Azuay', 'Ecuador', 'http://www.uazuay.edu.ec/'),
  ('Universidad del Bajío', 'México', 'http://www.ubac.edu.mx/'),
  ('Universidad del Bío-Bío', 'Chile', 'http://www.ubiobio.cl/'),
  ('Universidad del Caribe', 'República Dominicana', 'http://www.unicaribe.edu.do/'),
  ('Universidad del Cauca', 'Colombia', 'http://www.ucauca.edu.co/'),
  ('Universidad del CEMA', 'Argentina', 'https://ucema.edu.ar/'),
  ('Universidad del Centro de México', 'México', 'http://www.ucem.edu.mx/'),
  ('Universidad del Centro Educativo Latinoamericano Rosario', 'Argentina', 'http://www.ucel.edu.ar/'),
  ('Universidad del Cine - Buenos Aires', 'Argentina', 'http://www.ucine.edu.ar/'),
  ('Universidad del Cono Sur de las Américas', 'Paraguay', 'http://www.ucsa.edu.py/'),
  ('Universidad del Desarrollo', 'Chile', 'http://www.udesarrollo.cl/'),
  ('Universidad del Gran Rosario', 'Argentina', 'https://ugr.edu.ar/'),
  ('Universidad del Istmo', 'Guatemala', 'http://www.unis.edu.gt/'),
  ('Universidad del Istmo', 'Panamá', 'http://www.udi.edu/'),
  ('Universidad del Magdalena', 'Colombia', 'http://www.unimagdalena.edu.co/'),
  ('Universidad del Mar', 'Chile', 'http://www.udelmar.cl/'),
  ('Universidad del Mar', 'México', 'http://www.umar.mx/'),
  ('Universidad del Mayab', 'México', 'http://www.unimayab.edu.mx/'),
  ('Universidad del Museo Social Argentino', 'Argentina', 'http://www.umsa.edu.ar/'),
  ('Universidad del Noreste', 'México', 'http://www.une.edu.mx/'),
  ('Universidad del Noroeste', 'México', 'http://www.uno.mx/'),
  ('Universidad del Norte', 'Colombia', 'http://www.uninorte.edu.co/'),
  ('Universidad del Norte', 'México', 'http://www.un.edu.mx/'),
  ('Universidad del Norte', 'Paraguay', 'http://www.uninorte.edu.py/'),
  ('Universidad del Norte "Santo Tomás de Aquino"', 'Argentina', 'http://www.unsta.edu.ar/'),
  ('Universidad del Pacifico', 'Ecuador', 'http://www.upacifico.edu.ec/'),
  ('Universidad del Pacifico', 'Perú', 'http://www.up.edu.pe/'),
  ('Universidad del Pacífico', 'Chile', 'http://www.upacifico.cl/'),
  ('Universidad del Quindío', 'Colombia', 'http://www.uniquindio.edu.co/'),
  ('Universidad del Rosario', 'Colombia', 'http://www.urosario.edu.co/'),
  ('Universidad del Sagrado Corazon', 'Puerto Rico', 'http://www.sagrado.edu/'),
  ('Universidad del Salvador', 'Argentina', 'http://www.salvador.edu.ar/'),
  ('Universidad del Sinú', 'Colombia', 'http://www.unisinucartagena.edu.co/'),
  ('Universidad del Tepeyac', 'México', 'http://www.tepeyac.edu.mx/'),
  ('Universidad del Tolima', 'Colombia', 'http://www.ut.edu.co/'),
  ('Universidad del Turabo', 'Puerto Rico', 'http://www.ut.pr/'),
  ('Universidad del Turismo', 'Costa Rica', 'http://www.utur.ac.cr/'),
  ('Universidad del Valle de Atemajac', 'México', 'http://www.univa.mx/'),
  ('Universidad del Valle de Guatemala', 'Guatemala', 'http://www.uvg.edu.gt/'),
  ('Universidad del Valle de México', 'México', 'http://www.uvmnet.edu/'),
  ('Universidad del Valle de Puebla', 'México', 'http://members.rotfl.com/uvp/'),
  ('Universidad del Valle de Toluca', 'México', 'http://www.uvt.edu.mx/'),
  ('Universidad del Valle del Bravo', 'México', 'http://www.uvb.edu.mx/'),
  ('Universidad del Valle del Cauca', 'Colombia', 'http://www.univalle.edu.co/'),
  ('Universidad Diego Portales', 'Chile', 'http://www.udp.cl/'),
  ('Universidad Distrital "Francisco José de Caldas"', 'Colombia', 'http://www.udistrital.edu.co/'),
  ('Universidad Dominicana O&M', 'República Dominicana', 'http://www.udoym.edu.do/'),
  ('Universidad Dominico-Americana', 'República Dominicana', 'http://www.icda.edu.do/espanol/unicda/'),
  ('Universidad Don Bosco', 'El Salvador', 'http://www.cdb.edu.sv/'),
  ('Universidad Don Vasco', 'México', 'http://www.udv.edu.mx/'),
  ('Universidad Dr. Andreas Bello', 'El Salvador', 'http://www.unab.edu.sv/'),
  ('Universidad Dr. Jose Matias Delgado', 'El Salvador', 'http://www.ujmd.edu.sv/'),
  ('Universidad EAFIT', 'Colombia', 'http://www.eafit.edu.co/'),
  ('Universidad EAN', 'Colombia', 'https://universidadean.edu.co/'),
  ('Universidad El Bosque', 'Colombia', 'http://www.unbosque.edu.co/'),
  ('Universidad Empresarial', 'Costa Rica', 'http://www.unem.edu/internacional/'),
  ('Universidad Empresarial Siglo 21', 'Argentina', 'http://www.uesiglo21.edu.ar/'),
  ('Universidad Escuela Argentina de Negocios', 'Argentina', 'https://uean.edu.ar/'),
  ('Universidad España de Durango', 'México', 'http://www.unes.edu.mx/'),
  ('Universidad Especializada de Las Americas', 'Panamá', 'http://www.udelas.ac.pa/'),
  ('Universidad Estatal a Distancia', 'Costa Rica', 'http://www.uned.ac.cr/'),
  ('Universidad Estatal de Bolívar', 'Ecuador', 'http://www.ueb.isfun.net/'),
  ('Universidad Eugenio Maria de Hostos', 'República Dominicana', 'http://www.uniremhos.edu.do/'),
  ('Universidad Evangélica de El Salvador', 'El Salvador', 'http://www.uees.edu.sv/'),
  ('Universidad Experimental Felix Adam', 'República Dominicana', 'http://www.unefa.edu.do/'),
  ('Universidad Externado de Colombia', 'Colombia', 'http://www.uexternado.edu.co/'),
  ('Universidad Favaloro', 'Argentina', 'https://favaloro.edu.ar/'),
  ('Universidad Federico Henríquez y Carvajal', 'República Dominicana', 'http://www.ufhec.edu.do/'),
  ('Universidad Femenina del Sagrado Corazón', 'Perú', 'http://www.unife.edu.pe/'),
  ('Universidad Fidélitas', 'Costa Rica', 'http://www.ufidelitas.ac.cr/'),
  ('Universidad Finis Terrae', 'Chile', 'http://www.ufinis.cl/'),
  ('Universidad Franciscana de México', 'México', 'http://www.ufm.edu.mx/'),
  ('Universidad Francisco de Aguirre', 'Chile', 'http://www.unfa.cl/'),
  ('Universidad Francisco de Paula Santander', 'Colombia', 'http://www.ufps.edu.co/'),
  ('Universidad Francisco Gavidia', 'El Salvador', 'http://www.ufg.edu.sv/'),
  ('Universidad Francisco Marroquín', 'Guatemala', 'http://www.ufm.edu.gt/'),
  ('Universidad Franco-Mexicana', 'México', 'http://www.ufram.edu.mx/'),
  ('Universidad Fray Luca Paccioli', 'México', 'http://www.frayluca.edu.mx/'),
  ('Universidad Fundepos Alma Mater', 'Costa Rica', 'http://www.fundepos.ac.cr/'),
  ('Universidad Gabriela Mistral', 'Chile', 'http://www.ugm.cl/'),
  ('Universidad Galileo', 'Guatemala', 'http://www.galileo.edu/'),
  ('Universidad Gastón Dachary', 'Argentina', 'https://ugd.edu.ar/'),
  ('Universidad Guadalajara Lamar', 'México', 'https://lamar.mx/'),
  ('Universidad Hispanoamericana', 'Costa Rica', 'http://www.uhispanoamericana.ac.cr/'),
  ('Universidad Hispanoamericana', 'México', 'http://hispano.edu.mx/'),
  ('Universidad Hispanoamericana', 'Nicaragua', 'http://www.uhispam.edu.ni/'),
  ('Universidad Hospital Italiano', 'Argentina', 'https://instituto.hospitalitaliano.edu.ar/'),
  ('Universidad Iberoamericana', 'México', 'http://www.uia.mx/'),
  ('Universidad Iberoamericana', 'República Dominicana', 'http://www.unibe.edu.do/'),
  ('Universidad Iberoamericana de Ciencia y Tecnologia', 'Nicaragua', 'http://www.unicit.edu.ni/'),
  ('Universidad Iberoamericana de Ciencias y Tecnologia', 'Chile', 'http://www.unicit.cl/'),
  ('Universidad Iberoamericana, Campus León', 'México', 'http://www.leon.uia.mx/'),
  ('Universidad ICESI', 'Colombia', 'http://www.icesi.edu.co/'),
  ('Universidad INCCA de Colombia', 'Colombia', 'http://www.unincca.edu.co/'),
  ('Universidad Industrial de Santander', 'Colombia', 'http://www.uis.edu.co/'),
  ('Universidad Insurgentes Plantel León', 'México', 'http://www.uileon.edu.mx/'),
  ('Universidad Interamericana', 'República Dominicana', 'http://www.unica.edu.do/'),
  ('Universidad Interamericana de Educacion a Distancia de Panama', 'Panamá', 'http://www.uniedpa.com/'),
  ('Universidad Interamericana de Puerto Rico', 'Puerto Rico', 'http://www.inter.edu/'),
  ('Universidad Interamericana de Puerto Rico, Bayamón', 'Puerto Rico', 'http://www.bayamon.inter.edu/'),
  ('Universidad Interamericana de Puerto Rico, San Germán', 'Puerto Rico', 'http://www.sg.inter.edu/'),
  ('Universidad Intercontinental', 'México', 'http://www.uic.edu.mx/'),
  ('Universidad Internacional de Integración de América Latina', 'Nicaragua', 'http://www.unival.edu.ni/'),
  ('Universidad Internacional de las Américas', 'Costa Rica', 'http://www.uia.ac.cr/'),
  ('Universidad Internacional del Ecuador', 'Ecuador', 'http://www.internacional.edu.ec/'),
  ('Universidad Internacional Jefferson', 'México', 'https://www.jefferson.edu.mx/'),
  ('Universidad Internacional SEK, Quito', 'Ecuador', 'http://www.sek.edu/html/ecuador.html'),
  ('Universidad International SEK, Santiago', 'Chile', 'http://www.uisek.cl/'),
  ('Universidad Isaac Newton', 'Costa Rica', 'http://www.isaacnewtoncr.com/'),
  ('Universidad Isaac Newton', 'El Salvador', 'http://www.usin.edu.sv/'),
  ('Universidad ISALUD', 'Argentina', 'https://isalud.edu.ar/'),
  ('Universidad Itaca', 'México', 'http://www.i.edu.mx/'),
  ('Universidad José Cecilio del Valle', 'Honduras', 'http://www.ujcv.edu.hn/'),
  ('Universidad José Santos Ossa', 'Chile', 'http://www.ujso.cl/'),
  ('Universidad Justo Sierra', 'México', 'http://www.ujsierra.mx/'),
  ('Universidad Juárez Autónoma de Tabasco', 'México', 'http://www.ujat.mx/'),
  ('Universidad Juárez del Estado de Durango', 'México', 'http://www.ujed.mx/'),
  ('Universidad Jóse Vasconcelos', 'México', 'http://www.univas.edu.mx/'),
  ('Universidad Kino', 'México', 'http://www.unikino.mx/'),
  ('Universidad la Concordia', 'México', 'http://www.universidadlaconcordia.edu.mx/'),
  ('Universidad La Gran Colombia', 'Colombia', 'http://www.ugrancolombia.edu.co/'),
  ('Universidad La Republica', 'Chile', 'http://www.ulare.cl/'),
  ('Universidad La Salle', 'México', 'http://www.ulsa.edu.mx/'),
  ('Universidad La Salle Cuernavaca', 'México', 'http://www.ulsac.edu.mx/'),
  ('Universidad Laica "Eloy Alfaro" de Manabi', 'Ecuador', 'http://www.uleam.edu.ec/'),
  ('Universidad Laica "Vicente Rocafuerte" de Guayaquil', 'Ecuador', 'http://www.ulaicavr.com/'),
  ('Universidad Lasallista Benavente', 'México', 'http://www.ulsab.edu.mx/'),
  ('Universidad Latina', 'México', 'http://www.unla.edu.mx/'),
  ('Universidad Latina de Costa Rica', 'Costa Rica', 'http://www.ulatina.ac.cr/'),
  ('Universidad Latina de Panamá', 'Panamá', 'http://www.ulat.ac.pa/'),
  ('Universidad Latinoamericana', 'México', 'http://www.ula.edu.mx/'),
  ('Universidad Latinoamericana de Ciencia y Tecnologia, Panamá', 'Panamá', 'http://www.ulacit.ac.pa/'),
  ('Universidad Latinoamericana de Ciencia y Tecnología', 'Costa Rica', 'http://www.ulacit.ac.cr/'),
  ('Universidad Libre de Colombia', 'Colombia', 'http://www.unilibre.edu.co/'),
  ('Universidad Libre de Costa Rica', 'Costa Rica', 'http://www.ulicori.ac.cr/'),
  ('Universidad Los Angeles de Chimbote', 'Perú', 'http://www.uladech.edu.pe/'),
  ('Universidad Luterana Salvadorena', 'El Salvador', 'http://www.netcomsa.com/uls/'),
  ('Universidad Madero', 'México', 'http://www.umad.edu.mx/'),
  ('Universidad Maimónides', 'Argentina', 'http://www.maimonides.edu.ar/'),
  ('Universidad Marcelino Champagnat', 'Perú', 'http://www.champagnat.edu.pe/'),
  ('Universidad Mariana', 'Colombia', 'http://www.umariana.edu.co/'),
  ('Universidad Mariano Egaña', 'Chile', 'http://www.ume.cl/'),
  ('Universidad Mariano Gálvez', 'Guatemala', 'http://www.umg.edu.gt/'),
  ('Universidad Maritima de Chile', 'Chile', 'http://www.umaritima.cl/'),
  ('Universidad Mayor', 'Chile', 'http://www.umayor.cl/'),
  ('Universidad Mesoamericana de San Agustín', 'México', 'http://www.umsa.edu.mx/'),
  ('Universidad Metropolitana', 'Colombia', 'http://www.unimetro.edu.co/'),
  ('Universidad Metropolitana Castro Carazo', 'Costa Rica', 'http://www.umca.net/'),
  ('Universidad Metropolitana de Asunción', 'Paraguay', 'http://www.uma.edu.py/'),
  ('Universidad Metropolitana de Ciencias de la Educación', 'Chile', 'http://www.umce.cl/'),
  ('Universidad Metropolitana de Honduras', 'Honduras', 'http://www.unimetro.edu.hn/'),
  ('Universidad Metropolitana de Monterrey', 'México', 'http://www.umm.edu.mx/'),
  ('Universidad Metropolitana Latin Campus', 'México', 'http://www.umla.edu.mx/'),
  ('Universidad Mexicana', 'México', 'http://www.unimex.edu.mx/'),
  ('Universidad Mexicana del Noreste', 'México', 'http://www.umne.edu.mx/'),
  ('Universidad Michoacana de San Nicolás de Hidalgo', 'México', 'http://www.umich.mx/'),
  ('Universidad Miguel de Cervantes', 'Chile', 'http://www.ucervantes.cl/'),
  ('Universidad Militar Nueva Granada', 'Colombia', 'http://www.umng.edu.co/'),
  ('Universidad Modular Abierta', 'El Salvador', 'http://www.uma.edu.sv/'),
  ('Universidad Monsenor Oscar Arnulfo Romeo', 'El Salvador', 'http://www.umoar.edu.sv/'),
  ('Universidad Motolinía del Pedegral', 'México', 'http://www.universidadmotolinia.edu.mx/'),
  ('Universidad Motolinía del Pedregal', 'México', 'http://www.motolinia.com.mx/'),
  ('Universidad México Americana del Norte', 'México', 'http://www.uman.edu.mx/'),
  ('Universidad México Internacional', 'México', 'http://www.umi.edu.mx/'),
  ('Universidad Nacional', 'Costa Rica', 'http://www.una.ac.cr/'),
  ('Universidad Nacional Abierta y a Distancia', 'Colombia', 'http://www.unad.edu.co/'),
  ('Universidad Nacional Agraria', 'Nicaragua', 'http://www.una.edu.ni/'),
  ('Universidad Nacional Agraria de la Selva', 'Perú', 'http://www.unas.edu.pe/'),
  ('Universidad Nacional Agraria La Molina', 'Perú', 'http://www.lamolina.edu.pe/'),
  ('Universidad Nacional Andrés Bello', 'Chile', 'http://www.unab.cl/'),
  ('Universidad Nacional Arturo Jauretche', 'Argentina', 'https://unaj.edu.ar/'),
  ('Universidad Nacional Autonoma de Nicaragua', 'Nicaragua', 'http://www.unan.edu.ni/'),
  ('Universidad Nacional Autónoma de Honduras', 'Honduras', 'http://www.unah.edu.hn/'),
  ('Universidad Nacional Autónoma de México', 'México', 'http://www.unam.mx/'),
  ('Universidad Nacional Daniel Alcides Carrion', 'Perú', 'http://www.undac.edu.pe/'),
  ('Universidad Nacional de Asunción', 'Paraguay', 'http://www.una.py/'),
  ('Universidad Nacional de Avellaneda', 'Argentina', 'https://undav.edu.ar/'),
  ('Universidad Nacional de Cajamarca', 'Perú', 'http://www.unc.edu.pe/'),
  ('Universidad Nacional de Catamarca', 'Argentina', 'http://www.unca.edu.ar/'),
  ('Universidad Nacional de Chilecito', 'Argentina', 'https://www.undec.edu.ar/'),
  ('Universidad Nacional de Chimborazo', 'Ecuador', 'http://www.unach.edu.ec/'),
  ('Universidad Nacional de Colombia', 'Colombia', 'http://www.unal.edu.co/'),
  ('Universidad Nacional de Cuyo', 'Argentina', 'http://www.uncu.edu.ar/'),
  ('Universidad Nacional de Córdoba', 'Argentina', 'http://www.unc.edu.ar/'),
  ('Universidad Nacional de Educación Enrique Guzmán y Valle', 'Perú', 'http://www.une.edu.pe/'),
  ('Universidad Nacional de Entre Ríos', 'Argentina', 'http://www.uner.edu.ar/'),
  ('Universidad Nacional de Formosa', 'Argentina', 'http://www.unf.edu.ar/'),
  ('Universidad Nacional de General San Martín', 'Argentina', 'http://www.unsam.edu.ar/'),
  ('Universidad Nacional de General Sarmiento', 'Argentina', 'http://www.ungs.edu.ar/'),
  ('Universidad Nacional de Hurlingham', 'Argentina', 'https://unahur.edu.ar/'),
  ('Universidad Nacional de Ingenieria', 'Nicaragua', 'http://www.uni.edu.ni/'),
  ('Universidad Nacional de Ingeniería', 'Perú', 'http://www.uni.edu.pe/'),
  ('Universidad Nacional de José Clemente Paz', 'Argentina', 'https://unpaz.edu.ar/'),
  ('Universidad Nacional de Jujuy', 'Argentina', 'http://www.unju.edu.ar/'),
  ('Universidad Nacional de la Amazonía Peruana', 'Perú', 'http://www.unapiquitos.edu.pe/'),
  ('Universidad Nacional de La Libertad, Trujillo', 'Perú', 'http://www.unitru.edu.pe/'),
  ('Universidad Nacional de La Matanza', 'Argentina', 'http://www.unlam.edu.ar/'),
  ('Universidad Nacional de La Pampa', 'Argentina', 'http://www.unlpam.edu.ar/'),
  ('Universidad Nacional de la Patagonia "San Juan Bosco"', 'Argentina', 'http://www.unp.edu.ar/'),
  ('Universidad Nacional de la Patagonia Austral', 'Argentina', 'http://www.unpa.edu.ar/'),
  ('Universidad Nacional de La Plata', 'Argentina', 'http://www.unlp.edu.ar/'),
  ('Universidad Nacional de La Rioja', 'Argentina', 'http://www.unlar.edu.ar/'),
  ('Universidad Nacional de Lanús', 'Argentina', 'http://www.unla.edu.ar/'),
  ('Universidad Nacional de las Artes', 'Argentina', 'http://www.una.edu.ar/'),
  ('Universidad Nacional de Loja', 'Ecuador', 'http://www.unl.edu.ec/'),
  ('Universidad Nacional de Lomas de Zamora', 'Argentina', 'http://www.unlz.edu.ar/'),
  ('Universidad Nacional de los Comechingones', 'Argentina', 'https://unlc.edu.ar/'),
  ('Universidad Nacional de Luján', 'Argentina', 'http://www.unlu.edu.ar/'),
  ('Universidad Nacional de Mar del Plata', 'Argentina', 'http://www.mdp.edu.ar/'),
  ('Universidad Nacional de Misiones', 'Argentina', 'http://www.unam.edu.ar/'),
  ('Universidad Nacional de Moreno', 'Argentina', 'https://www.unm.edu.ar/'),
  ('Universidad Nacional de Pilar', 'Argentina', 'https://unpilar.edu.ar/'),
  ('Universidad Nacional de Piura', 'Perú', 'http://www.unp.edu.pe/'),
  ('Universidad Nacional de Quilmes', 'Argentina', 'http://www.unq.edu.ar/'),
  ('Universidad Nacional de Rafaela', 'Argentina', 'https://unraf.edu.ar/'),
  ('Universidad Nacional de Rosario', 'Argentina', 'http://www.unr.edu.ar/'),
  ('Universidad Nacional de Río Cuarto', 'Argentina', 'http://www.unrc.edu.ar/'),
  ('Universidad Nacional de Río Negro', 'Argentina', 'https://www.unrn.edu.ar/'),
  ('Universidad Nacional de Río Tercero', 'Argentina', 'https://unrt.edu.ar/'),
  ('Universidad Nacional de Salta', 'Argentina', 'http://www.unsa.edu.ar/'),
  ('Universidad Nacional de San Agustin', 'Perú', 'http://www.unsa.edu.pe/'),
  ('Universidad Nacional de San Antonio Abad', 'Perú', 'http://www.unsaac.edu.pe/'),
  ('Universidad Nacional de San Cristóbal de Huamanga', 'Perú', 'http://www.unsch.edu.pe/'),
  ('Universidad Nacional de San Juan', 'Argentina', 'http://www.unsj.edu.ar/'),
  ('Universidad Nacional de San Luis', 'Argentina', 'http://www.unsl.edu.ar/'),
  ('Universidad Nacional de San Martín', 'Perú', 'http://www.unsm.edu.pe/'),
  ('Universidad Nacional de Santa - Chimbote', 'Perú', 'http://www.uns.edu.pe/'),
  ('Universidad Nacional de Santiago del Estero', 'Argentina', 'http://www.unse.edu.ar/'),
  ('Universidad Nacional de Tres de Febrero', 'Argentina', 'http://www.untref.edu.ar/'),
  ('Universidad Nacional de Tucumán', 'Argentina', 'http://www.unt.edu.ar/'),
  ('Universidad Nacional de Tumbes', 'Perú', 'http://www.untumbes.edu.pe/'),
  ('Universidad Nacional de Ucayali', 'Perú', 'http://www.unu.edu.pe/'),
  ('Universidad Nacional de Villa María', 'Argentina', 'https://www.unvm.edu.ar/'),
  ('Universidad Nacional de Villa Mercedes', 'Argentina', 'https://www.unvime.edu.ar/'),
  ('Universidad Nacional del Altiplano', 'Perú', 'http://www.unap.edu.pe/'),
  ('Universidad Nacional del Alto Uruguay', 'Argentina', 'https://unau.edu.ar/'),
  ('Universidad Nacional del Callao', 'Perú', 'http://www.unac.edu.pe/'),
  ('Universidad Nacional del Centro de la Provincia de Buenos Aires', 'Argentina', 'http://www.unicen.edu.ar/'),
  ('Universidad Nacional del Centro del Perú', 'Perú', 'http://www.uncp.edu.pe/'),
  ('Universidad Nacional del Chaco Austral', 'Argentina', 'https://uncaus.edu.ar/'),
  ('Universidad Nacional del Comahue', 'Argentina', 'http://www.uncoma.edu.ar/'),
  ('Universidad Nacional del Delta', 'Argentina', 'https://undelta.edu.ar/'),
  ('Universidad Nacional del Este', 'Paraguay', 'http://www.une.edu.py/'),
  ('Universidad Nacional del Litoral', 'Argentina', 'http://www.unl.edu.ar/'),
  ('Universidad Nacional del Nordeste', 'Argentina', 'http://www.unne.edu.ar/'),
  ('Universidad Nacional del Noroeste de la Provincia de Buenos Aires', 'Argentina', 'http://www.unnoba.edu.ar/'),
  ('Universidad Nacional del Oeste', 'Argentina', 'https://uno.edu.ar/'),
  ('Universidad Nacional del Sur', 'Argentina', 'http://www.uns.edu.ar/'),
  ('Universidad Nacional del Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'Argentina', 'https://untdf.edu.ar/'),
  ('Universidad Nacional Evangélica', 'República Dominicana', 'http://www.unev-rd.edu.do/'),
  ('Universidad Nacional Federico Villarreal', 'Perú', 'http://www.unfv.edu.pe/'),
  ('Universidad Nacional Guillermo Brown', 'Argentina', 'https://unab.edu.ar/'),
  ('Universidad Nacional Hermilio Valdizan', 'Perú', 'http://www.unheval.edu.pe/'),
  ('Universidad Nacional Jorge Basadre Grohmann', 'Perú', 'http://www.unjbg.edu.pe/'),
  ('Universidad Nacional José Faustino Sánchez Carrión', 'Perú', 'http://www.unjfsc.edu.pe/'),
  ('Universidad Nacional Mayor de San Marcos', 'Perú', 'http://www.unmsm.edu.pe/'),
  ('Universidad Nacional Pedro Henríquez Ureña', 'República Dominicana', 'http://www.unphu.edu.do/'),
  ('Universidad Nacional Pedro Ruíz Gallo', 'Perú', 'http://www.unprg.edu.pe/'),
  ('Universidad Nacional San Antonio de Areco', 'Argentina', 'https://unsada.edu.ar/'),
  ('Universidad Nacional San Luis Gonzaga', 'Perú', 'http://www.unica.edu.pe/'),
  ('Universidad Nacional Santiago Antúnez de Mayolo', 'Perú', 'http://www.unasam.edu.pe/'),
  ('Universidad Nicaragüense de Ciencia y Tecnológica', 'Nicaragua', 'http://www.ucyt.edu.ni/'),
  ('Universidad Norbert Wiener', 'Perú', 'http://www.uwiener.edu.pe/'),
  ('Universidad Notarial Argentina', 'Argentina', 'http://www.universidadnotarial.edu.ar/'),
  ('Universidad Nueva San Salvador', 'El Salvador', 'http://www.unssa.edu.sv/'),
  ('Universidad Nuevo Mundo', 'México', 'http://www.unum.edu.mx/'),
  ('Universidad Obrera de Mexico', 'México', 'http://www.uom.edu.mx/'),
  ('Universidad Odontológica Dominicana', 'República Dominicana', 'http://www.uod.edu.do/'),
  ('Universidad Olmeca', 'México', 'http://www.olmeca.edu.mx/'),
  ('Universidad ORT Uruguay', 'Uruguay', 'http://www.ort.edu.uy/'),
  ('Universidad Panamericana', 'Guatemala', 'http://www.upana.edu.gt/'),
  ('Universidad Panamericana', 'México', 'http://www.up.mx/'),
  ('Universidad Panamericana de San Salvador', 'El Salvador', 'http://www.upan.edu.sv/'),
  ('Universidad para la Cooperación Internacional', 'Costa Rica', 'http://www.uci.ac.cr/'),
  ('Universidad Particular de Chiclayo', 'Perú', 'http://www.udch.edu.pe/'),
  ('Universidad Particular Inca Garcilaso de la Vega', 'Perú', 'http://www.uigv.edu.pe/'),
  ('Universidad Pedagogica Nacional', 'Colombia', 'http://www.pedagogica.edu.co/'),
  ('Universidad Pedagógica "José Martí", Camagüey', 'Cuba', 'http://www.ispcmw.rimed.cu/'),
  ('Universidad Pedagógica de El Salvador', 'El Salvador', 'http://www.universidadpedagogica.com/'),
  ('Universidad Pedagógica Nacional', 'Argentina', 'https://unipe.edu.ar/'),
  ('Universidad Pedagógica Nacional', 'México', 'http://www.upn.mx/'),
  ('Universidad Pedagógica Nacional "Francisco Morazán"', 'Honduras', 'http://www.upnfm.edu.hn/'),
  ('Universidad Pedagógica Nacional, Unidad León', 'México', 'http://www.lef.upn.mx/'),
  ('Universidad Pedagógica Veracruzana', 'México', 'http://www.secupv.org/'),
  ('Universidad Pedagógica y Tecnológica de Colombia', 'Colombia', 'http://www.uptc.edu.co/'),
  ('Universidad Peruana Cayetano Heredia', 'Perú', 'http://www.upch.edu.pe/'),
  ('Universidad Peruana de Ciencias Aplicadas', 'Perú', 'http://www.upc.edu.pe/'),
  ('Universidad Peruana de Ciencias e Informática', 'Perú', 'http://www.upci.edu.pe/'),
  ('Universidad Peruana Union', 'Perú', 'http://www.upeu.edu.pe/'),
  ('Universidad Piloto de Colombia', 'Colombia', 'http://www.unipiloto.edu.co/'),
  ('Universidad Politecnica de Nicaragua', 'Nicaragua', 'http://www.upoli.edu.ni/'),
  ('Universidad Politécnica de El Salvador', 'El Salvador', 'http://www.upes.edu.sv/'),
  ('Universidad Politécnica Salesiana', 'Ecuador', 'http://www.ups.edu.ec/'),
  ('Universidad Pontificia Bolivariana', 'Colombia', 'http://www.upb.edu.co/'),
  ('Universidad Popular Autonóma del Estado de Puebla', 'México', 'http://www.upaep.mx/'),
  ('Universidad Popular de Nicaragua (UPONIC)', 'Nicaragua', 'http://www.uponic.edu.ni/'),
  ('Universidad Popular del Cesar', 'Colombia', 'http://www.unicesar.edu.co/'),
  ('Universidad Privada Antenor Orrego', 'Perú', 'http://www.upao.edu.pe/'),
  ('Universidad Privada de Tacna', 'Perú', 'http://www.upt.edu.pe/'),
  ('Universidad Privada del Este', 'Paraguay', 'http://www.upe.edu.py/'),
  ('Universidad Privada del Norte', 'Perú', 'http://www.upnorte.edu.pe/'),
  ('Universidad Privada Juan Mejía Baca', 'Perú', 'http://www.umb.edu.pe/'),
  ('Universidad Privada Los Andes', 'Perú', 'http://www.upla.edu.pe/'),
  ('Universidad Privada San Juan Bautista', 'Perú', 'http://www.upsjb.edu.pe/'),
  ('Universidad Privada San Pedro', 'Perú', 'http://www.usanpedro.edu.pe/'),
  ('Universidad Privada Sergio Bernales', 'Perú', 'http://www.upsb.edu.pe/'),
  ('Universidad Provincial de Ezeiza', 'Argentina', 'https://web.upe.edu.ar/'),
  ('Universidad Rafael Landívar', 'Guatemala', 'http://www.url.edu.gt/'),
  ('Universidad Regiomontana', 'México', 'http://www.ur.mx/'),
  ('Universidad Regional del Sureste', 'México', 'http://www.urse.edu.mx/'),
  ('Universidad Regional Miguel Hidalgo', 'México', 'http://www.urmh.edu.mx/'),
  ('Universidad Ricardo Palma', 'Perú', 'http://www.urp.edu.pe/'),
  ('Universidad Rural de Guatemala', 'Guatemala', 'http://www.urural.edu.gt/'),
  ('Universidad Salesiana', 'México', 'http://www.universidadsalesiana.edu.mx/'),
  ('Universidad Salvadorena "Alberto Masferrer"', 'El Salvador', 'http://www.usam.edu.sv/'),
  ('Universidad San Carlos', 'Paraguay', 'https://www.sancarlos.edu.py/'),
  ('Universidad San Francisco de Quito', 'Ecuador', 'http://www.usfq.edu.ec/'),
  ('Universidad San Ignacio de Loyola', 'Perú', 'http://www.sil.edu.pe/'),
  ('Universidad San Juan de la Cruz', 'Costa Rica', 'http://www.sjdlc.com/'),
  ('Universidad San Marcos', 'Costa Rica', 'http://www.usam.ac.cr/'),
  ('Universidad San Martin de Porres', 'Perú', 'http://www.usmp.edu.pe/'),
  ('Universidad San Pablo', 'Perú', 'http://www.usp.edu.pe/'),
  ('Universidad San Sebastian', 'Chile', 'http://www.uss.cl/'),
  ('Universidad Santa Fe', 'México', 'http://www.usf.com.mx/'),
  ('Universidad Santa María Campus Guayaquil', 'Ecuador', 'http://www.usm.edu.ec/'),
  ('Universidad Santa Paula', 'Costa Rica', 'http://www.uspsantapaula.com/'),
  ('Universidad Santiago de Cali', 'Colombia', 'http://www.usaca.edu.co/'),
  ('Universidad Santo Tomás', 'Chile', 'http://www.ust.cl/'),
  ('Universidad Santo Tomás', 'Colombia', 'http://www.usta.edu.co/'),
  ('Universidad Sergio Arboleda', 'Colombia', 'http://www.usergioarboleda.edu.co/'),
  ('Universidad Señor de Sipán', 'Perú', 'http://www.uss.edu.pe/'),
  ('Universidad Simón Bolivar', 'México', 'http://www.usb.edu.mx/'),
  ('Universidad Surcolombiana', 'Colombia', 'http://www.usurcolombia.com/'),
  ('Universidad Tecmilenio', 'México', 'https://tecmilenio.mx/'),
  ('Universidad Tecnologica "Vicente Perez Rosales"', 'Chile', 'http://www.uvipro.cl/'),
  ('Universidad Tecnologica de la Mixteca', 'México', 'http://www.utm.mx/'),
  ('Universidad Tecnologica de Nezahualcoyotl', 'México', 'http://www.utneza.edu.mx/'),
  ('Universidad Tecnologica Israel', 'Ecuador', 'http://www.uisrael.ec/'),
  ('Universidad Tecnológica América', 'Ecuador', 'http://www.unita.edu.ec/'),
  ('Universidad Tecnológica Centroamericana', 'Honduras', 'http://www.unitec.edu/'),
  ('Universidad Tecnológica de El Salvador', 'El Salvador', 'http://www.utec.edu.sv/'),
  ('Universidad Tecnológica de Honduras', 'Honduras', 'http://www.uth.hn/'),
  ('Universidad Tecnológica de los Andes de Apurímac', 'Perú', 'http://www.utea.edu.pe/'),
  ('Universidad Tecnológica de México', 'México', 'http://www.unitec.mx/'),
  ('Universidad Tecnológica de Panamá', 'Panamá', 'http://www.utp.ac.pa/'),
  ('Universidad Tecnológica de Pereira', 'Colombia', 'http://www.utp.edu.co/'),
  ('Universidad Tecnológica de Santiago', 'República Dominicana', 'http://www.utesa.edu/'),
  ('Universidad Tecnológica del Choco "Diego Luis Cordoba"', 'Colombia', 'http://www.utch.edu.co/'),
  ('Universidad Tecnológica del Peru', 'Perú', 'http://www.utp.edu.pe/'),
  ('Universidad Tecnológica del Sur', 'República Dominicana', 'http://www.utesur.edu.do/'),
  ('Universidad Tecnológica Equinoccial', 'Ecuador', 'http://www.ute.edu.ec/'),
  ('Universidad Tecnológica Indoamérica', 'Ecuador', 'http://www.indoamerica.edu.ec/'),
  ('Universidad Tecnológica Metropolitana', 'Chile', 'http://www.utem.cl/'),
  ('Universidad Tecnológica Nacional', 'Argentina', 'http://www.utn.edu.ar/'),
  ('Universidad Tecnológica Oteima', 'Panamá', 'http://www.oteima.ac.pa/'),
  ('Universidad Tecnológica San Antonio de Machala', 'Ecuador', 'http://www.utsam.edu.ec/'),
  ('Universidad Torcuato di Tella', 'Argentina', 'http://www.utdt.edu/'),
  ('Universidad Técnica "Federico Santa María"', 'Chile', 'http://www.utfsm.cl/'),
  ('Universidad Técnica de Ambato', 'Ecuador', 'http://www.uta.edu.ec/'),
  ('Universidad Técnica de Babahoyo', 'Ecuador', 'http://www.utb.edu.ec/'),
  ('Universidad Técnica de Cotopaxi', 'Ecuador', 'http://www.utc.edu.ec/'),
  ('Universidad Técnica de Esmeraldas "Luis Vargas Torres"', 'Ecuador', 'http://www.utelvt.edu.ec/'),
  ('Universidad Técnica de Machala', 'Ecuador', 'http://www.utmachala.edu.ec/'),
  ('Universidad Técnica de Manabí', 'Ecuador', 'http://www.utm.edu.ec/'),
  ('Universidad Técnica del Norte', 'Ecuador', 'http://www.utn.edu.ec/'),
  ('Universidad Técnica Estatal de Quevedo', 'Ecuador', 'http://www.uteq.edu.ec/'),
  ('Universidad Técnica Federico Santa María', 'Chile', 'https://usm.cl'),
  ('Universidad Técnica Latinoamericana', 'El Salvador', 'http://www.utla.edu.sv/'),
  ('Universidad Técnica Particular de Loja', 'Ecuador', 'http://www.utpl.edu.ec/'),
  ('Universidad Valle del Grijalva', 'México', 'http://www.uvg1.net/'),
  ('Universidad Veracruzana', 'México', 'http://www.uv.mx/'),
  ('Universidad Veritas', 'Costa Rica', 'http://www.uveritas.ac.cr/'),
  ('Universidad Xicotepetl', 'México', 'http://www.uxac.edu.mx/'),
  ('Universidade Anhembi Morumbi - UAM', 'Brasil', 'https://portal.anhembi.br/'),
  ('Universidade Bandeirante de São Paulo', 'Brasil', 'http://www.uniban.br/'),
  ('Universidade Braz Cubas', 'Brasil', 'http://www.brazcubas.br/'),
  ('Universidade Camilo Castelo Branco', 'Brasil', 'http://www.unicastelo.br/'),
  ('Universidade Candido Mendes', 'Brasil', 'http://www.candidomendes.br/'),
  ('Universidade Castelo Branco', 'Brasil', 'http://www.castelobranco.br/'),
  ('Universidade Católica de Brasília', 'Brasil', 'http://www.ucb.br/'),
  ('Universidade Católica de Goiás', 'Brasil', 'http://www.ucg.br/'),
  ('Universidade Católica de Pelotas', 'Brasil', 'http://www.ucpel.tche.br/'),
  ('Universidade Católica de Pernambuco', 'Brasil', 'http://www.unicap.br/'),
  ('Universidade Católica de Petrópolis', 'Brasil', 'http://www.ucp.br/'),
  ('Universidade Católica de Santos', 'Brasil', 'http://www.unisantos.com.br/'),
  ('Universidade Católica do Salvador', 'Brasil', 'http://www.ucsal.br/'),
  ('Universidade Católica Dom Bosco', 'Brasil', 'http://www.unibosco.br/'),
  ('Universidade Cidade de São Paulo', 'Brasil', 'http://www.unicid.br/'),
  ('Universidade Comunitária da Região de Chapecó - Unochapecó', 'Brasil', 'https://unochapeco.edu.br'),
  ('Universidade Cruzeiro do Sul', 'Brasil', 'http://www.unicsul.br/'),
  ('Universidade da Amazônia', 'Brasil', 'http://www.unama.br/'),
  ('Universidade da Região da Campanha', 'Brasil', 'http://www.urcamp.tche.br/'),
  ('Universidade de Alfenas', 'Brasil', 'http://www.unifenas.br/'),
  ('Universidade de Brasília', 'Brasil', 'http://www.unb.br/'),
  ('Universidade de Caxias do Sul', 'Brasil', 'http://www.ucs.tche.br/'),
  ('Universidade de Cruz Alta', 'Brasil', 'http://www.unicruz.tche.br/'),
  ('Universidade de Fortaleza', 'Brasil', 'http://www.unifor.br/'),
  ('Universidade de Franca', 'Brasil', 'http://www.unifran.br/'),
  ('Universidade de Guarulhos', 'Brasil', 'http://www.ung.br/'),
  ('Universidade de Itaúna', 'Brasil', 'http://web.prover.com.br/fui/'),
  ('Universidade de Marília', 'Brasil', 'http://www.unimar.br/'),
  ('Universidade de Mogi das Cruzes', 'Brasil', 'http://www.umc.br/'),
  ('Universidade de Nova Iguaçu', 'Brasil', 'http://www.unig.br/'),
  ('Universidade de Passo Fundo', 'Brasil', 'http://www.upf.tche.br/'),
  ('Universidade de Pernambuco', 'Brasil', 'http://www.upe.br/'),
  ('Universidade de Ribeirão Preto', 'Brasil', 'http://www.unaerp.br/'),
  ('Universidade de Santa Cruz do Sul', 'Brasil', 'http://www.unisc.br/'),
  ('Universidade de Santo Amaro', 'Brasil', 'http://www.unisa.br/'),
  ('Universidade de São Paulo', 'Brasil', 'http://www.usp.br/'),
  ('Universidade de Taubaté', 'Brasil', 'http://www.unitau.br/'),
  ('Universidade de Tocantins', 'Brasil', 'http://www.pop-to.rnp.br/'),
  ('Universidade de Uberaba', 'Brasil', 'http://www.uniube.br/'),
  ('Universidade do Amazonas', 'Brasil', 'http://www.fua.br/'),
  ('Universidade do Estado da Bahia', 'Brasil', 'http://www.uneb.br/'),
  ('Universidade do Estado de Santa Catarina', 'Brasil', 'http://www.udesc.br/'),
  ('Universidade do Estado do Rio de Janeiro', 'Brasil', 'http://www.uerj.br/'),
  ('Universidade do Estado do Rio Grande do Norte', 'Brasil', 'http://www.uern.br/'),
  ('Universidade do Extremo Sul Catarinense', 'Brasil', 'http://www.unesc.rct-sc.br/'),
  ('Universidade do Grande Rio', 'Brasil', 'http://www.unigranrio.br/'),
  ('Universidade do Oeste de Santa Catarina', 'Brasil', 'http://www.unoesc.edu.br/'),
  ('Universidade do Oeste Paulista', 'Brasil', 'http://www.unoeste.br/'),
  ('Universidade do Rio de Janeiro', 'Brasil', 'http://www.unirio.br/'),
  ('Universidade do Sagrado Coração', 'Brasil', 'http://www.usc.br/'),
  ('Universidade do Sul de Santa Catarina', 'Brasil', 'http://www.unisul.br/'),
  ('Universidade do Vale do Itajaí', 'Brasil', 'http://www.univali.rct-sc.br/'),
  ('Universidade do Vale do Paraíba – Univap', 'Brasil', 'https://www.univap.br/univap/'),
  ('Universidade Estadual da Paraíba', 'Brasil', 'http://www.uepb.edu.br/'),
  ('Universidade Estadual de Campinas', 'Brasil', 'http://www.unicamp.br/'),
  ('Universidade Estadual de Feira de Santana', 'Brasil', 'http://www.uefs.br/'),
  ('Universidade Estadual de Londrina', 'Brasil', 'http://www.uel.br/'),
  ('Universidade Estadual de Maringá', 'Brasil', 'http://www.uem.br/'),
  ('Universidade Estadual de Montes Claros', 'Brasil', 'http://www.unimontes.br/'),
  ('Universidade Estadual de Ponta Grossa', 'Brasil', 'http://www.uepg.br/'),
  ('Universidade Estadual de Santa Cruz', 'Brasil', 'http://www.uesc.br/'),
  ('Universidade Estadual do Ceará', 'Brasil', 'http://www.uece.br/'),
  ('Universidade Estadual do Maranhão', 'Brasil', 'http://www.uema.br/'),
  ('Universidade Estadual do Norte do Parana', 'Brasil', 'https://uenp.edu.br/'),
  ('Universidade Estadual do Norte Fluminense', 'Brasil', 'http://www.uenf.br/'),
  ('Universidade Estadual do Oeste do Paraná', 'Brasil', 'http://www.unioeste.br/'),
  ('Universidade Estadual do Piauí', 'Brasil', 'http://www.uespi.br/'),
  ('Universidade Estadual do Vale do Acaraú', 'Brasil', 'http://www.uvanet.br/'),
  ('Universidade Estadual Paulista', 'Brasil', 'http://www.unesp.br/'),
  ('Universidade Estadual Sudoeste da Bahia', 'Brasil', 'http://www.uesb.br/'),
  ('Universidade Estácio de Sá', 'Brasil', 'http://www.estacio.br/'),
  ('Universidade Federal da Bahia', 'Brasil', 'http://www.ufba.br/'),
  ('Universidade Federal da Grande Dourados', 'Brasil', 'http://www.ufgd.edu.br/'),
  ('Universidade Federal da Paraíba', 'Brasil', 'http://www.ufpb.br/'),
  ('Universidade Federal de Alagoas', 'Brasil', 'http://www.ufal.br/'),
  ('Universidade Federal de Campina Grande', 'Brasil', 'http://www.ufcg.edu.br/'),
  ('Universidade Federal de Goiás', 'Brasil', 'http://www.ufg.br/'),
  ('Universidade Federal de Itajubá', 'Brasil', 'https://unifei.edu.br/'),
  ('Universidade Federal de Juiz de Fora', 'Brasil', 'http://www.ufjf.br/'),
  ('Universidade Federal de Lavras', 'Brasil', 'http://www.ufla.br/'),
  ('Universidade Federal de Mato Grosso', 'Brasil', 'http://www.ufmt.br/'),
  ('Universidade Federal de Mato Grosso do Sul', 'Brasil', 'http://www.ufms.br/'),
  ('Universidade Federal de Minas Gerais', 'Brasil', 'http://www.ufmg.br/'),
  ('Universidade Federal de Ouro Preto', 'Brasil', 'http://www.ufop.br/'),
  ('Universidade Federal de Pelotas', 'Brasil', 'http://www.ufpel.tche.br/'),
  ('Universidade Federal de Pernambuco', 'Brasil', 'http://www.ufpe.br/'),
  ('Universidade Federal de Rondônia', 'Brasil', 'http://www.unir.br/'),
  ('Universidade Federal de Roraima', 'Brasil', 'http://www.technet.com.br/vestibular/'),
  ('Universidade Federal de Santa Catarina', 'Brasil', 'http://www.ufsc.br/'),
  ('Universidade Federal de Santa Maria', 'Brasil', 'http://www.ufsm.br/'),
  ('Universidade Federal de Sergipe', 'Brasil', 'http://www.ufs.br/'),
  ('Universidade Federal de São Carlos', 'Brasil', 'http://www.ufscar.br/'),
  ('Universidade Federal de São João del-Rei', 'Brasil', 'https://www.ufsj.edu.br/'),
  ('Universidade Federal de São Paulo', 'Brasil', 'http://www.epm.br/'),
  ('Universidade Federal de Uberlândia', 'Brasil', 'http://www.ufu.br/'),
  ('Universidade Federal de Viçosa', 'Brasil', 'http://www.ufv.br/'),
  ('Universidade Federal do ABC', 'Brasil', 'http://www.ufabc.edu.br/'),
  ('Universidade Federal do Acre', 'Brasil', 'http://www.ufac.br/'),
  ('Universidade Federal do Amapá', 'Brasil', 'http://www.unifap.br/'),
  ('Universidade Federal do Ceará', 'Brasil', 'http://www.ufc.br/'),
  ('Universidade Federal do Espírito Santo', 'Brasil', 'http://www.ufes.br/'),
  ('Universidade Federal do Maranhão', 'Brasil', 'http://www.ufma.br/'),
  ('Universidade Federal do Paraná', 'Brasil', 'http://www.ufpr.br/'),
  ('Universidade Federal do Pará', 'Brasil', 'http://www.ufpa.br/'),
  ('Universidade Federal do Piauí', 'Brasil', 'http://www.ufpi.br/'),
  ('Universidade Federal do Rio de Janeiro', 'Brasil', 'http://www.ufrj.br/'),
  ('Universidade Federal do Rio Grande', 'Brasil', 'http://www.furg.br/'),
  ('Universidade Federal do Rio Grande do Norte', 'Brasil', 'http://www.ufrn.br/'),
  ('Universidade Federal do Rio Grande do Sul', 'Brasil', 'http://www.ufrgs.br/'),
  ('Universidade Federal do Triângulo Mineiro', 'Brasil', 'http://www.uftm.edu.br/'),
  ('Universidade Federal do Vale do São Francisco', 'Brasil', 'http://www.univasf.edu.br/'),
  ('Universidade Federal dos Vales do Jequitinhonha e Mucuri', 'Brasil', 'http://www.ufvjm.edu.br'),
  ('Universidade Federal Fluminense', 'Brasil', 'http://www.uff.br/'),
  ('Universidade Federal Rural de Pernambuco', 'Brasil', 'http://www.ufrpe.br/'),
  ('Universidade Federal Rural do Rio de Janeiro', 'Brasil', 'http://www.ufrrj.br/'),
  ('Universidade Franciscana', 'Brasil', 'https://www.ufn.edu.br/'),
  ('Universidade Gama Filho', 'Brasil', 'http://www.ugf.br/'),
  ('Universidade Ibirapuera', 'Brasil', 'http://www.unib.br/'),
  ('Universidade Luterana do Brasil', 'Brasil', 'http://www.ulbra.br/'),
  ('Universidade Mackenzie', 'Brasil', 'http://www.mackenzie.br/'),
  ('Universidade Metodista de Piracicaba', 'Brasil', 'http://www.unimep.br/'),
  ('Universidade Metropolitana de Santos', 'Brasil', 'http://www.unimes.com.br/'),
  ('Universidade para o Desenvolvimento do Alto Vale do Itajaí', 'Brasil', 'http://www.unidavi.rct-sc.br/'),
  ('Universidade Paulista', 'Brasil', 'http://www.unip-objetivo.br/'),
  ('Universidade Potiguar', 'Brasil', 'http://www.unp.br/'),
  ('Universidade Regional de Blumenau', 'Brasil', 'http://www.furb.rct-sc.br/'),
  ('Universidade Regional do Cariri', 'Brasil', 'http://www.urca.br/'),
  ('Universidade Regional do Noroeste do Estado do Rio Grande do Sul', 'Brasil', 'http://www.unijui.tche.br/'),
  ('Universidade Regional Integrada do Alto Uruguai e das Missões', 'Brasil', 'http://www.uri.br/'),
  ('Universidade Salgado de Oliveira', 'Brasil', 'http://www.universo.br/'),
  ('Universidade Salvador', 'Brasil', 'http://www.unifacs.br/'),
  ('Universidade Santa Cecília dos Bandeirantes', 'Brasil', 'http://www.stcecilia.br/'),
  ('Universidade Santa Úrsula', 'Brasil', 'http://www.usu.br/'),
  ('Universidade São Francisco', 'Brasil', 'http://www.usf.br/'),
  ('Universidade São Judas Tadeu', 'Brasil', 'http://www.saojudas.br/'),
  ('Universidade São Marcos', 'Brasil', 'http://www.smarcos.br/'),
  ('Universidade Tecnológica Federal do Paraná', 'Brasil', 'https://www.utfpr.edu.br/'),
  ('Universidade Tiradentes', 'Brasil', 'http://www.unit.br/'),
  ('Universidade Vale do Rio Doce', 'Brasil', 'http://www.univale.br/'),
  ('Universidade Vale do Rio dos Sinos', 'Brasil', 'http://www.unisinos.br/'),
  ('Universidade Veiga de Almeida', 'Brasil', 'http://www.uva.br/'),
  ('Universidade Virtual do Estado de São Paulo', 'Brasil', 'https://univesp.br/'),
  ('University for Peace', 'Costa Rica', 'http://www.upeace.org/'),
  ('Victoria International University', 'Panamá', 'http://www.viu.edu.pa/'),
  ('West Coast University (WCU)', 'Panamá', 'http://www.westcoastuniversity-edu.com/'),
  ('Westhill University', 'México', 'http://www.westhill.edu.mx/')
on conflict (name, country) do nothing;
